#!/bin/bash

set -eu

title=${1:-}

gnuplot << EOF

set terminal pdf;
set output 'hist.pdf';
set key outside
set title "$title"
set xlabel "x"
plot \
  "hist_0.dat" w l lw 3 ,\
  "hist_1.dat" w l lw 3 ,\

EOF
